#pragma once

#define INSTALLER_DBUS_INTERFACE_NAME "org.appimage.Services1.Installer"
#define INSTALLER_DBUS_OBJECT_PATH "/org/appimage/Services1/Installer"
#define INSTALLER_DBUS_METHOD_INSTALL INSTALLER_DBUS_INTERFACE_NAME".install"
#define INSTALLER_DBUS_METHOD_UNINSTALL INSTALLER_DBUS_INTERFACE_NAME".uninstall"



