// libraries
#include <QDBusConnection>
#include <QDebug>

// local
#include "LauncherDBusInterface.h"
#include <LauncherService.h>

// generated by `qt5_add_dbus_adaptor` cmake function
#include "launcheradaptor.h"

LauncherDBusInterface::LauncherDBusInterface(QObject* parent) : QObject(parent) {
    new LauncherAdaptor(this);
    QDBusConnection dbus = QDBusConnection::sessionBus();
    bool operationSucceed;
    operationSucceed = dbus.registerObject(LAUNCHER_DBUS_OBJECT_PATH, this);
    if (!operationSucceed)
        qCritical() << "Unable to register d-bus object: " << LAUNCHER_DBUS_OBJECT_PATH;

    operationSucceed = dbus.registerService(LAUNCHER_DBUS_INTERFACE_NAME);
    if (!operationSucceed)
        qCritical() << "Unable to register d-bus service: " << LAUNCHER_DBUS_INTERFACE_NAME;

}

bool LauncherDBusInterface::registerApp(const QString& appImagePath) const {
    qDebug() << __FUNCTION__ << " : " << appImagePath;
    QString newPath = removeUriProtocolFromPath(appImagePath);
    return launcherService.registerApp(newPath.toStdString());
}

bool LauncherDBusInterface::unregisterApp(const QString& appImagePath) const {
    qDebug() << __FUNCTION__ << " : " << appImagePath;
    QString newPath = removeUriProtocolFromPath(appImagePath);
    return launcherService.unregisterApp(newPath.toStdString());
}

bool LauncherDBusInterface::isRegistered(const QString& appImagePath) const {
    qDebug() << __FUNCTION__ << " : " << appImagePath;
    QString newPath = removeUriProtocolFromPath(appImagePath);
    return launcherService.isRegistered(newPath.toStdString());
}

bool LauncherDBusInterface::launch(const QString& appImagePath, const QStringList& args) const {
    qDebug() << __FUNCTION__ << " : " << appImagePath;
    QString newPath = removeUriProtocolFromPath(appImagePath);
    return launcherService.launch(newPath.toStdString(), args);
}

QString LauncherDBusInterface::removeUriProtocolFromPath(const QString& path) {
    if (path.startsWith("file://"))
        return path.mid(7);
    else
        return path;
}

LauncherDBusInterface::~LauncherDBusInterface() = default;
