#pragma once

#define LAUNCHER_DBUS_INTERFACE_NAME "org.appimage.Services1.Launcher"
#define LAUNCHER_DBUS_OBJECT_PATH "/org/appimage/Services1/Launcher"
#define LAUNCHER_DBUS_METHOD_LAUNCH LAUNCHER_DBUS_INTERFACE_NAME".launch"
#define LAUNCHER_DBUS_METHOD_REGISTER_APP LAUNCHER_DBUS_INTERFACE_NAME".registerApp"
#define LAUNCHER_DBUS_METHOD_UNREGISTER_APP LAUNCHER_DBUS_INTERFACE_NAME".unregisterApp"


