// libraries
#include <QDBusConnection>

// local
#include "DBusInterface.h"

// generated by `qt5_add_dbus_adaptor` cmake function
#include "servicesadaptor.h"

DBusInterface::DBusInterface(QObject* parent) : QObject(parent) {
    new LauncherAdaptor(this);
    QDBusConnection dbus = QDBusConnection::sessionBus();
    dbus.registerObject("/org/appimage/Services/Launcher", this);
    dbus.registerService("org.appimage.Services.Launcher");
}

bool DBusInterface::registerApp(const QString& appImagePath) {
    return false;
}

bool DBusInterface::unregisterApp(const QString& appImagePath) {
    return false;
}

DBusInterface::~DBusInterface() = default;
